global:
  scrape_interval: 15s
  evaluation_interval: 15s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093
rule_files:
  - rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "remote_collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["192.168.31.101:9100"]
  - job_name: 'nginx-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.31.101:9113']
