---
- name: Install nginx and Upload my Web Page
  hosts: all
  become: yes

  vars:
    source_file: index.html
    destin_file: /var/www/html

  tasks:
  - name: Install nginx WebServer
    apt: name=nginx state=latest

  - name: Copy file
    copy: src={{source_file}} dest={{destin_file}} mode=0555
    notify: Restart nginx

  - name: Start
    service: name=nginx state=started enabled=yes

  handlers:
  - name: Restart nginx
    service: name=nginx state=restarted
